### PR TITLE
ENH: hierarchy of EtherCAT terminals

### LINKED ISSUE #4: Remove packaging pin
This is handled upsream in docs-versions-menu v0.5.1: 
https://github.com/goerz/docs_versions_menu/releases/tag/v0.5.1
https://github.com/pcdshub/twincat-docs-template/blob/3a40b145fa7ae4561eed7bfbd52583b886c11858/requirements.txt#L8

### PR DESCRIPTION
**Pull request by klauer**
This update adds a hierarchy of EtherCAT terminals in the form of nested numbered lists:

image

Also closes #4

### CODE REVIEW

**Comment by klauer** [comment]
This may require some fixes if it fails CI jobs, but we can address it then.

An example of this in the PLC summary which is now set up for a daily cron job:
https://pcdshub.github.io/plc-summary/ethercat.html

**Comment by ZLLentz** [comment]
That all project IO summary pages is pretty wild, I like it

**Review by ZLLentz — APPROVED** [review]
I see no reason not to click approve, the output looks clean and there's not much to scrutinize in the diff

**Review by tangkong — APPROVED** [review]
Output is long, but it looks good 👍

**Pull request merged**
